name_list: ['PELVIS',
            'RWRIST', 'LWRIST', 'RHIP', 'LHIP', 'RKNEE', 'LKNEE', 'RANKLE', 'LANKLE', 'RFOOT', 'LFOOT',
            'RHAND', 'LHAND', 'RELBOW', 'LELBOW', 'RSHOULDER', 'LSHOULDER',
            'HEAD', 'THORAX', 'HDTP', 'REAR', 'LEAR', 'C7', 'C7_d', 'SS',
            'RAP_b', 'RAP_f', 'LAP_b', 'LAP_f', 'RLE', 'RME', 'LLE', 'LME', 'RMCP2', 'RMCP5', 'LMCP2', 'LMCP5']


#eval_key: 'dict'
#estimate_file: {'validate': '/Users/leyangwen/Documents/Pose/paper/37kpts_v1/validate/X3D.npy',
#                 'test': '/Users/leyangwen/Documents/Pose/paper/37kpts_v1/test/X3D.npy'}
#
#GT_file: '/Users/leyangwen/Documents/Pose/paper/VEHS_6D_downsample2_keep1.pkl'  # 66 kpts, not matching

estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20-fps-pretrain-normal/VEHS7M-validate-best-gt2d/X3D.npy'

eval_key: 'validate'

## normal
#GT_file: '/Volumes/Z/RTMPose/37kpts_freeze_v3/20fps/MB_checkpoints/VEHS_6D_downsample5_keep1_37_v2_RTM2D.pkl'
#estimate_file: '/Volumes/Z/RTMPose/37kpts_freeze_v3/20fps/lab_Videos_freeze_backbone_epoch_best_20fps/normal/X3D.npy'

#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-normal-6/VEHS7M-validate/X3D.npy'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20-fps-pretrain-normal/VEHS7M-validate-best-gt2d/X3D.npy'

## pitch-correct
GT_file: '/Volumes/Z/RTMPose/37kpts_freeze_v3/20fps/MB_GT/VEHS_6D_downsample5_keep1_37_v2_pitch_correct_RTM2D.pkl'
# limb loss added
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20-fps-finetune-pitch-correct-6/VEHS7M-validate/X3D.npy'

# angle loss added
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-pitch-correct-angleLoss-7/VEHS7M-Validate/X3D.npy'

# OG loss
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-pitch-correct-9/VEHS7M-validate/X3D.npy'