name_list: ['PELVIS',
            'RWRIST', 'LWRIST', 'RHIP', 'LHIP', 'RKNEE', 'LKNEE', 'RANKLE', 'LANKLE', 'RFOOT', 'LFOOT',
            'RHAND', 'LHAND', 'RELBOW', 'LELBOW', 'RSHOULDER', 'LSHOULDER',
            'HEAD', 'THORAX', 'HDTP', 'REAR', 'LEAR', 'C7', 'C7_d', 'SS',
            'RAP_b', 'RAP_f', 'LAP_b', 'LAP_f', 'RLE', 'RME', 'LLE', 'LME', 'RMCP2', 'RMCP5', 'LMCP2', 'LMCP5']

eval_key: 'validate'
GT_file: None
# if frame number not same, try switching between validate and median

# normal
#estimate_file: '/Volumes/Z/RTMPose/37kpts_freeze_v3/20fps/Ricks_Videos_freeze_backbone_epoch_best_20fps/normal/X3D.npy'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-normal-6/Industry/X3D.npy'

## pitch-correct
#limb loss added
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20-fps-finetune-pitch-correct-6/Industry/X3D.npy'

# angle loss added
estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-pitch-correct-angleLoss-7/Industry_2/X3D.npy'
