name_list: ['PELVIS',
            'RWRIST', 'LWRIST', 'RHIP', 'LHIP', 'RKNEE', 'LKNEE', 'RANKLE', 'LANKLE', 'RFOOT', 'LFOOT',
            'RHAND', 'LHAND', 'RELBOW', 'LELBOW', 'RSHOULDER', 'LSHOULDER',
            'HEAD', 'THORAX', 'HDTP', 'REAR', 'LEAR', 'C7', 'C7_d', 'SS',
            'RAP_b', 'RAP_f', 'LAP_b', 'LAP_f', 'RLE', 'RME', 'LLE', 'LME', 'RMCP2', 'RMCP5', 'LMCP2', 'LMCP5']

eval_key: 'validate'

# RTMW-V4, no 3d, 2d only
#GT_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-1-OG/Industry_both/exp_2b_industry_videos_20fps/rtmpose_v5-2b_20fps_industry_37kpts_v2.pkl'
GT_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v4/20fps/Ricks_Videos_RTMW_freeze_backbone_neck_merged_epoch_best/rtmpose_v4_20fps_industry_1_37kpts_v2.pkl'
#GT_file: None

# if frame number not same, try switching between validate and test

# normal
#estimate_file: '/Volumes/Z/RTMPose/37kpts_freeze_v3/20fps/Ricks_Videos_freeze_backbone_epoch_best_20fps/normal/X3D.npy'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-normal-6/Industry/X3D.npy'

## pitch-correct
#limb loss added: RTM-V3 MB-V6
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20-fps-finetune-pitch-correct-6/Industry/X3D.npy'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-pitch-correct-angleLoss-6/Industry_2/X3D.npy'

# angle loss added: RTM-V3 MB-V7
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-pitch-correct-angleLoss-7/Industry_2/X3D.npy'

# RTMW-V4 MB-V7
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-pitch-correct-angleLoss-7/RTMW-v4/Industry_2/X3D.npy'

# OG loss: RTM-V3 MB-V9
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/20fps-finetune-pitch-correct-9/Industry_2/X3D.npy'

# RTMW-V5-2b  Industry 1-2 in same, rick12 first
#estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-1-OG/Industry_both/X3D.npy'
#estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-normal-1-OG/Industry_both/X3D.npy'
#estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-2-limbLoss/Industry_both_2/X3D.npy'
#estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-normal-2-limbLoss/Industry_both/X3D.npy'
#estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-3-angleLoss/Industry_both/X3D.npy'

estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-5-angleLossV2-only/Industry_both/X3D.npy'
#estimate_file: '/Volumes/Z/RTMPose/37kpts_rtmw_v5/20fps/RTMW37kpts_v2_20fps-finetune-pitch-correct-5-angleLossV2-only/Industry_both_noflip/X3D.npy'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/smoothed/X3D_smooth.npy'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/RTMW37kpts_v2_20fps-finetune-pitch-correct-6-center-angleLoss/Industry_both/X3D.npy'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/RTMW37kpts_v2_20fps-finetune-pitch-correct-5-centerLoss/Industry_both/X3D.npy'