joints:
  mid: ['HDTP', 'REAR', 'LEAR', 'HEAD', 'C7', 'C7_d', 'SS', 'THORAX', 'PELVIS']
  topR: ['RAP_b', 'RAP_f', 'RSHOULDER', 'RLE', 'RME', 'RELBOW', 'RWRIST', 'RMCP2', 'RMCP5', 'RHAND']
  topL: ['LAP_b', 'LAP_f', 'LSHOULDER', 'LLE', 'LME', 'LELBOW', 'LWRIST', 'LMCP2', 'LMCP5', 'LHAND']
  botR: ['RHIP', 'RKNEE', 'RANKLE', 'RFOOT']
  botL: ['LHIP', 'LKNEE', 'LANKLE', 'LFOOT']

parent:
  mid: ['HEAD', 'HEAD', 'HEAD', 'C7', 'C7_d', 'THORAX', 'THORAX', 'PELVIS', None]
  topR: ['RSHOULDER', 'RSHOULDER', 'THORAX', 'RELBOW', 'RELBOW', 'RSHOULDER', 'RELBOW', 'RHAND', 'RHAND', 'RWRIST']
  topL: ['LSHOULDER', 'LSHOULDER', 'THORAX', 'LELBOW', 'LELBOW', 'LSHOULDER', 'LELBOW', 'LHAND', 'LHAND', 'LWRIST']
  botR: ['PELVIS', 'RHIP', 'RKNEE', 'RANKLE']
  botL: ['PELVIS', 'LHIP', 'LKNEE', 'LANKLE']
