lower_bone_acronym:
  PELO: Pelvis Origin
  PELP: Pelvis Proximal
  PELA: Pelvis Anterior
  PELL: Pelvis Lateral
  RFEO: Right Femur Origin
  RFEP: Right Femur Proximal
  RFEA: Right Femur Anterior
  RFEL: Right Femur Lateral
  LFEO: Left Femur Origin
  LFEP: Left Femur Proximal
  LFEA: Left Femur Anterior
  LFEL: Left Femur Lateral
  RTIO: Right Tibia Origin
  RTIP: Right Tibia Proximal
  RTIA: Right Tibia Anterior
  RTIL: Right Tibia Lateral
  LTIO: Left Tibia Origin
  LTIP: Left Tibia Proximal
  LTIA: Left Tibia Anterior
  LTIL: Left Tibia Lateral
  RFOO: Right Foot Origin
  RFOP: Right Foot Proximal
  RFOA: Right Foot Anterior
  RFOL: Right Foot Lateral
  LFOO: Left Foot Origin
  LFOP: Left Foot Proximal
  LFOA: Left Foot Anterior
  LFOL: Left Foot Lateral
  RTOO: Right Toe Origin
  RTOP: Right Toe Proximal
  RTOA: Right Toe Anterior
  RTOL: Right Toe Lateral
  LTOO: Left Toe Origin
  LTOP: Left Toe Proximal
  LTOA: Left Toe Anterior
  LTOL: Left Toe Latera

upper_bone_acronym:
  HEDO: Head Origin
  HEDP: Head Proximal
  HEDA: Head Anterior
  HEDL: Head Lateral
  TRXO: Thorax Origin
  TRXP: Thorax Proximal
  TRXA: Thorax Anterior
  TRXL: Thorax Lateral
  CSPO: C Spine Origin
  CSPP: C Spine Proximal
  CSPA: C Spine Anterior
  CSPL: C Spine Lateral
  SACO: Sacrum Origin
  SACP: Sacrum Proximal
  SACA: Sacrum Anterior
  SACL: Sacrum Lateral
  RCLO: Right Clavicle Origin
  RCLP: Right Clavicle Proximal
  RCLA: Right Clavicle Anterior
  RCLL: Right Clavicle Lateral
  LCLO: Left Clavicle Origin
  LCLP: Left Clavicle Proximal
  LCLA: Left Clavicle Anterior
  LCLL: Left Clavicle Lateral
  RHUO: Right Humerus Origin
  RHUP: Right Humerus Proximal
  RHUA: Right Humerus Anterior
  RHUL: Right Humerus Lateral
  LHUO: Left Humerus Origin
  LHUP: Left Humerus Proximal
  LHUA: Left Humerus Anterior
  LHUL: Left Humerus Lateral
  RRAO: Right Radius Origin
  RRAP: Right Radius Proximal
  RRAA: Right Radius Anterior
  RRAL: Right Radius Lateral
  LRAO: Left Radius Origin
  LRAP: Left Radius Proximal
  LRAA: Left Radius Anterior
  LRAL: Left Radius Lateral
  RHNO: Right Hand Origin
  RHNP: Right Hand Proximal
  RHNA: Right Hand Anterior
  RHNL: Right Hand Lateral
  LHNO: Left Hand Origin
  LHNP: Left Hand Proximal
  LHNA: Left Hand Anterior
  LHNL: Left Hand Lateral
  RFIO: Right Finger Origin
  RFIP: Right Finger Proximal
  RFIA: Right Finger Anterior
  RFIL: Right Finger Lateral
  LFIO: Left Finger Origin
  LFIP: Left Finger Proximal
  LFIA: Left Finger Anterior
  LFIL: Left Finger Lateral
  RTBO: Right Thumb Origin
  RTBP: Right Thumb Proximal
  RTBA: Right Thumb Anterior
  RTBL: Right Thumb Lateral
  LTBO: Left Thumb Origin
  LTBP: Left Thumb Proximal
  LTBA: Left Thumb Anterior
  LTBL: Left Thumb Lateral

joint_center_acronym:
  LHJC: Left Hip Joint Centre
  RHJC: Right Hip Joint Centre
  LKJC: Left Knee Joint Centre
  RKJC: Right Knee Joint Centre
  LAJC: Left Ankle Joint Centre
  RAJC: Right Ankle Joint Centre
  LSJC: Left Shoulder Joint Centre
  RSJC: Right Shoulder Joint Centre
  LEJC: Left Elbow Joint Centre
  REJC: Right Elbow Joint Centre
  LWJC: Left Wrist Joint Centre
  RWJC: Right Wrist Joint Centre

com_acronym:
  PelvisCOM: Pelvis COM
  LeftFemurCOM: Left Femur COM
  LeftTibiaCOM: Left Tibia COM
  LeftFootCOM: Left Foot COM
  RightFemurCOM: Right Femur COM
  RightTibiaCOM: Right Tibia COM
  RightFootCOM: Right Foot COM
  ThoraxCOM: Thorax COM
  HeadCOM: Head COM
  LeftHumerusCOM: Left Humerus COM
  LeftRadiusCOM: Left Radius COM
  LeftHandCOM: Left Hand COM
  RightHumerusCOM: Right Humerus COM
  RightRadiusCOM: Right Radius COM
  RightHandCOM: Right Hand COM
  CentreOfMass: Centre Of Mass
  CentreOfMassFloor: Centre Of Mass Floor

plugingait_marker_acronym:
  LFHD: Left front head
  RFHD: Right front head
  LBHD: Left back head
  RBHD: Right back head
  C7: Back of neck
  T10: Upper back
  CLAV: Clavicle
  STRN: Sternum
  LBAK: Left back
  RBAK: Right back
  LSHO: Left shoulder
  LUPA: Left upper arm
  LELB: Left elbow
  LFRA: Left forearm
  LWRA: Left wrist bar thumb side
  LWRB: Left wrist bar pinkie side
  LFIN: Left finger
  RSHO: Right shoulder
  RUPA: Right upper arm
  RELB: Right elbow
  RFRA: Right forearm
  RWRA: Right wrist bar thumb side
  RWRB: Right wrist bar pinkie side
  RFIN: Right finger
  SACR: Sacral wand marker
  LASI: Left ASIS
  RASI: Right ASIS
  LPSI: Left PSIS
  RPSI: Right PSIS
  LTHI: Left thigh wand marker
  LKNE: Left knee
  LTIB: Left tibial wand marker
  LANK: Left ankle
  LHEE: Left heel
  LTOE: Left toe
  RTHI: Right thigh wand marker
  RKNE: Right knee
  RTIB: Right tibial wand marker
  RANK: Right ankle
  RHEE: Right heel
  RTOE: Right toe
  LKAX: Left knee axis
  LKD1: Left knee device 1
  LKD2: Left knee device 2
  RKAX: Right knee axis
  RKD1: Right knee device 1
  RKD2: Right knee device 2

VEHS_marker_acronym:
  HDEY: Eye center
  HDTP: Head top
  RNKT: Right neck top
  LNKT: Left neck top
  LPIK: Left pinky
  RPIK: Right pinky

VEHS_virtualPt_acronym:
  LEYE: Left eye
  REYE: Right eye
  RMFO: Right middle finger origin
  LMFO: Left middle finger origin
  LPKO: Left pinky origin
  RPKO: Right pinky origin
  NKTP: Neck top
  NKBT: Neck bottom
  FHEC: Front head center
  BHEC: Back head center
  RHEC: Right head center
  LHEC: Left head center
  HDCC: Head center
  HTPO: Head top origin

