name_list: ['HIP_c', 'RHIP', 'RKNEE', 'RANKLE', 'LHIP', 'LKNEE', 'LANKLE', 'T8',
            'H36M_THORAX', 'H36M_NECK', 'H36M_HEAD', 'LSHOULDER', 'LELBOW', 'LWRIST', 'RSHOULDER', 'RELBOW', 'RWRIST']

GT_name_list: ['PELVIS', 'RWRIST', 'LWRIST', 'RHIP', 'LHIP', 'RKNEE', 'LKNEE', 'RANKLE', 'LANKLE', 'RFOOT', 'LFOOT', 'RHAND', 'LHAND', 'RELBOW', 'LELBOW', 'RSHOULDER', 'LSHOULDER',
            'HEAD', 'THORAX', 'HDTP', 'REAR', 'LEAR', 'C7', 'C7_d', 'SS', 'RAP_b', 'RAP_f', 'LAP_b', 'LAP_f', 'RLE', 'RME', 'LLE', 'LME', 'RMCP2', 'RMCP5', 'LMCP2', 'LMCP5']

GT_file: '/Volumes/Z/RTMPose/37kpts_freeze_v3/20fps/MB_GT/VEHS_6D_downsample5_keep1_37_v2_pitch_correct_RTM2D.pkl'
#GT_file: '/Users/leyangwen/Downloads/scratch_pose/H36M-17kpts/VEHS-GT/VEHS_3D_downsample5_keep1_H36M_17.pkl'

#
eval_key: 'validate'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/H36M-17kpts/MB_train_H36M_gt2D_3DPose/VEHS7M-validate/X3D.npy'
estimate_file: '/Users/leyangwen/Downloads/scratch_pose/H36M-17kpts/FT_MB_release_MB_ft_h36m/VEHS7M-validate-1920x1200/X3D.npy'



#eval_key: 'test'
#estimate_file: '/Users/leyangwen/Downloads/scratch_pose/H36M-17kpts/FT_MB_release_MB_ft_h36m/VEHS7M-test-1920x1200/X3D.npy'
