
name_list: ['PELVIS', 'torso', 'head', 'right_upper_arm', 'right_lower_arm',
 'right_hand', 'left_upper_arm', 'left_lower_arm', 'left_hand',
 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot', '1', '2', '3']


start_positions:
  - [8.5, 4, 0.0]

end_positions:
  - [2.5, 2.5, 0.0]

fps: 20
keyframe_detect: False
no_experiments: 1

# S01 - bag_l
weight: 20.41
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+bag_l/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - bag_s
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+bag_s/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - bag_slide
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+bag_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - bag_step
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+bag_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - box_l_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+box_l_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - box_l_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+box_l_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - box_s_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+box_s_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - box_s_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+box_s_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - box_slide
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+box_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - box_step
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+box_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - handle_l_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+handle_l_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - handle_l_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+handle_l_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - handle_s_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+handle_s_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - handle_s_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+handle_s_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - handle_slide
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+handle_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - handle_step
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+handle_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - timber_l
weight: 2.27
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+timber_l/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - timber_s
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+timber_s/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - timber_slide
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+timber_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - timber_step
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+timber_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S01 - timber_step_2
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S01/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S01+__+timber_step_2/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - bag_l
weight: 20.41
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+bag_l/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - bag_s
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+bag_s/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - bag_slide
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+bag_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - bag_step
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+bag_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - bag_step_2
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+bag_step_2/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - box_l_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+box_l_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - box_l_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+box_l_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - box_s_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+box_s_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - box_s_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+box_s_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - box_slide
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+box_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - box_step
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+box_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - handle_l_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+handle_l_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - handle_l_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+handle_l_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - handle_s_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+handle_s_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - handle_s_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+handle_s_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - handle_slide
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+handle_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - handle_step
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+handle_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - handle_step_2
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+handle_step_2/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - timber_l
weight: 2.27
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+timber_l/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - timber_s
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+timber_s/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - timber_slide
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+timber_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S02 - timber_step
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S02/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S02+__+timber_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - bag_l
weight: 20.41
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+bag_l/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - bag_s
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+bag_s/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - bag_slide
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+bag_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - bag_step
weight: 11.34
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+bag_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - box_l_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+box_l_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - box_l_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+box_l_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - box_s_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+box_s_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - box_s_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+box_s_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - box_slide
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+box_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - box_step
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+box_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - handle_l_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+handle_l_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - handle_l_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+handle_l_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - handle_s_10lbs
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+handle_s_10lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - handle_s_20lbs
weight: 9.07
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+handle_s_20lbs/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - handle_slide
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+handle_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - handle_step
weight: 4.54
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+handle_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - timber_l
weight: 2.27
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+timber_l/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - timber_s
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+timber_s/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - timber_slide
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+timber_slide/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []

# S03 - timber_step
weight: 1.36
estimate_file: '/Volumes/Y/intervension_eval_data/worker_motion/issac/S03/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_worker_motion+__+S03+__+timber_step/phys_humanoid_v5/isaac_formatted_motion.csv'
lift_start: []
lift_end: []