name_list: ['PELVIS', 'torso', 'head', 'right_upper_arm', 'right_lower_arm',
 'right_hand', 'left_upper_arm', 'left_lower_arm', 'left_hand',
 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot', '1', '2', '3']


start_positions:
  - [8.5, 4, 0.0]

end_positions:
  - [2.5, 2.5, 0.0]

fps: 20
keyframe_detect: False
mute_lowers: True
lift_detect: True
no_experiments: 1
start_offset: 25

experiments:
  - name: terrain_step_v1_bag_s
    weight: 11.34
    estimate_file: '/Volumes/Y/intervention_eval_data/recommended_motion/exp_terrain_step_v1/Terrain-bag-s1/joint_states.csv'
    lift_start: []
    lift_end: [-1]

  - name: terrain_step_v1_box_s1
    weight: 4.54
    estimate_file: '/Volumes/Y/intervention_eval_data/recommended_motion/exp_terrain_step_v1/Terrain-box-s1/joint_states.csv'
    lift_start: []
    lift_end: [-1]

  - name: terrain_step_v1_box_s2
    weight: 4.54
    estimate_file: '/Volumes/Y/intervention_eval_data/recommended_motion/exp_terrain_step_v1/Terrain-box-s2/joint_states.csv'
    lift_start: []
    lift_end: [-1]

  - name: terrain_step_v1_handle_s1
    weight: 4.54
    estimate_file: '/Volumes/Y/intervention_eval_data/recommended_motion/exp_terrain_step_v1/Terrain-handle-s1/joint_states.csv'
    lift_start: []
    lift_end: [-1]

  - name: terrain_step_v1_handle_s2
    weight: 4.54
    estimate_file: '/Volumes/Y/intervention_eval_data/recommended_motion/exp_terrain_step_v1/Terrain-handle-s2/joint_states.csv'
    lift_start: []
    lift_end: [-1]

  - name: terrain_step_v1_timber_s
    weight: 1.36
    estimate_file: '/Volumes/Y/intervention_eval_data/recommended_motion/exp_terrain_step_v1/Terrain-timber-s1/joint_states.csv'
    lift_start: []
    lift_end: [-1]