name_list: ['nose','left_ear','right_ear','left_shoulder','right_shoulder','left_elbow','right_elbow','left_wrist','right_wrist','left_hip','right_hip','left_knee','right_knee','left_ankle','right_ankle','left_index','left_middle_mcp','left_pinky','right_index','right_middle_mcp','right_pinky','PELVIS','thorax','head'] # This is a set of rtmpose keypoints for the new training of the multistride and the MotionBert package

GT_file: None
eval_key: 'validate'

estimate_file: 'W:\VEHS\Testing_Videos_and_rtmpose_results\Testing_Videos_and_rtmpose_results\kps_133_fps_20\pitch_corrected\industry_RTM2d_tilt_corrected.npy'