name_list: ['Wrist', 'Thumb_0', 'Thumb_1', 'Thumb_2', 'Thumb_3',
            'Index_0', 'Index_1', 'Index_2', 'Index_3',
            'Middle_0', 'Middle_1', 'Middle_2', 'Middle_3',
            'Ring_0', 'Ring_1', 'Ring_2', 'Ring_3',
            'Pinky_0', 'Pinky_1', 'Pinky_2', 'Pinky_3']

GT_file: '/Volumes/Extreme SSD/Gloved Hands/lab_rtmpose_hand_for_MB.pkl'

#eval_key: 'validate'
#estimate_file: '/Volumes/Extreme SSD/Gloved Hands/MB Output/left/MB_out_left.npy'

eval_key: 'test'
estimate_file: '/Volumes/Extreme SSD/Gloved Hands/MB Output/right/MB_out_right.npy'

