name_list: ['Wrist', 'Thumb_0', 'Thumb_1', 'Thumb_2', 'Thumb_3',
            'Index_0', 'Index_1', 'Index_2', 'Index_3',
            'Middle_0', 'Middle_1', 'Middle_2', 'Middle_3',
            'Ring_0', 'Ring_1', 'Ring_2', 'Ring_3',
            'Pinky_0', 'Pinky_1', 'Pinky_2', 'Pinky_3']

#GT_file: '/Users/leyangwen/Documents/Hand/motionbert_dict_20240618.pkl'
#GT_file: '/Users/leyangwen/Documents/Hand/motionbert_dict_20240826.pkl'
#GT_file: '/Users/leyangwen/Documents/Hand/Rokoko_hand_3D_downsample5_keep1.pkl'
GT_file: 'W:\VEHS\Rokoko_hand_3D_downsample1_keep1.pkl'

eval_key: 'test'

estimate_file: None

