name_list: ['Wrist', 'Thumb_0', 'Thumb_1', 'Thumb_2', 'Thumb_3',
            'Index_0', 'Index_1', 'Index_2', 'Index_3',
            'Middle_0', 'Middle_1', 'Middle_2', 'Middle_3',
            'Ring_0', 'Ring_1', 'Ring_2', 'Ring_3',
            'Pinky_0', 'Pinky_1', 'Pinky_2', 'Pinky_3']

#GT_file: '/Users/leyangwen/Documents/Hand/Rokoko_hand_3D_downsample1_keep1.pkl'
#estimate_file: '/Users/leyangwen/Documents/Hand/X3D.npy'

GT_file: 'W:\VEHS\hand_pose\MB_input\Rokoko_2\Rokoko_hand_3D_downsample1_keep1.pkl'
estimate_file: 'W:\VEHS\hand_pose\MB_output\Rokoko_2\test_X3D.npy'

eval_key: 'test'



