train_ratio: 0.7
val_ratio: 0.2
test_ratio: 0.1

#base_folder: W:\VEHS\VEHS data collection round 3\processed
base_folder: W:\VEHS\VEHS data collection round 3\processed
val_keyword: ['S01', 'S05']  # 3.1, 3.5
test_keyword: ['S09']  # 3.9
#val_keyword: ['LeyangWen', 'DanLi']  # 3.1, 3.5
#test_keyword: ['RuiNie']  # 3.9