train_ratio: 0.6
val_ratio: 0.2
test_ratio: 0.2

base_folder: W:\VEHS\VEHS data collection round 3\processed
val_keyword: ['LeyangWen', 'DanLi']  # 3.1, 3.5
test_keyword: ['JohnSohn', 'RuiNie']  # 3.4, 3.9