joints:
  mid: ['Pelvis', 'Head', 'Thorax']
  botL: ['Left Hip Joint Centre', 'Left Knee Joint Centre', 'Left Ankle Joint Centre', 'Left heel', 'Left toe']
  topL: ['Left Shoulder Joint Centre', 'Left Elbow Joint Centre', 'Left Wrist Joint Centre', 'Left Hand Origin']
  botR: ['Right Hip Joint Centre', 'Right Knee Joint Centre', 'Right Ankle Joint Centre', 'Right heel', 'Right toe'
  topR: ['Right Shoulder Joint Centre', 'Right Elbow Joint Centre', 'Right Wrist Joint Centre', 'Right Hand Origin']

parent:
  mid: [None, 'Thorax', 'Pelvis']
  botL: ['Pelvis', 'Left Hip Joint Centre', 'Left Knee Joint Centre', 'Left Ankle Joint Centre', 'Left Ankle Joint Centre']
  topL: ['Thorax', 'Left Shoulder Joint Centre', 'Left Elbow Joint Centre', 'Left Wrist Joint Centre']
  botR: ['Pelvis', 'Right Hip Joint Centre', 'Right Knee Joint Centre', 'Right Ankle Joint Centre']
  topR: ['Thorax', 'Right Shoulder Joint Centre', 'Right Elbow Joint Centre', 'Right Wrist Joint Centre']
