
name_list: ['PELVIS', 'torso', 'head', 'right_upper_arm', 'right_lower_arm',
 'right_hand', 'left_upper_arm', 'left_lower_arm', 'left_hand',
 'right_thigh', 'right_shin', 'right_foot', 'left_thigh', 'left_shin', 'left_foot', '1', '2', '3']


start_positions:
  - [8.5, 4, 0.25]

end_positions:
  - [2.5, 2.5, 0.25]

fps: 30

density: 156.25
dim: [0.4, 0.4, 0.4]  # w l h
keyframe_detect: False

no_experiments: 2
estimate_file: '/home/leyang/Documents/TokenHSI/tokenhsi/data/dataset_carry/motions/MMH/dashboard_pickUp/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_imitation_motions+__+Terrain_lift+__+dashboard+__+bad+__+bad/phys_humanoid_v3/isaac_formatted_motion.csv'
lift_start: [62, 54]
lift_end: [87, 112]


# estimate_file: '/home/leyang/Documents/TokenHSI/tokenhsi/data/dataset_carry/motions/MMH/dashboard_pickUp/+__+home+__+leyang+__+Documents+__+SMPLest-X+__+demo+__+result_imitation_motions+__+Terrain_lift+__+dashboard+__+good+__+good/phys_humanoid_v3/isaac_formatted_motion.csv'
# lift_start: [53, 48]
# lift_end: [76, 79]
